name: CI
on: [push, pull_request]

jobs:
  native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - run: cargo check
      - run: cargo fmt -- --check
      - run: cargo clippy -- -D warnings
      - run: cargo test

  wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - run: cargo build --release --target wasm32-unknown-unknown
      - uses: actions/upload-artifact@v3
        with:
          name: wasm-build
          path: target/wasm32-unknown-unknown/release/
